management.endpoint.beans.enabled: true
management.endpoint.health.group.foo.include: fooState
management.endpoint.health.group.buss.roles: AAA
management.endpoint.health.group.bar.exclude: oneState, twoState

my.map.props.map-of-maps.foo.bar.key: test1_value
my.map.props.map-of-strings.aaa.bbb.ccc: test1_value
my.map.props.enumkeys.key1: test1_value

my.map.props:
  enumkeys.key2: test1_value1
  map-of-strings.ddd.eee.fff: test1_value1

logging.group.first: com.*
logging.group.second: javax.*
logging.group.third: org.*

logging.level.first: debug
logging.level.second: debug
logging.level.third: debug

logging.level.com.example.demo: trace

my.nested.props.nested.deep.deep-nested-str: test1_aaa
my.nested.props.nested.nested-str: test1_bbb
my.nested.props.top-str: test1_ccc
